export { initWebGPU, getGpuContext } from './context';
export { createTerrainShader, invertMat4 } from './terrain-renderer';
export { Scene } from './scene';
export { createTerrainMaterial, createSeaMaterial, createSkyMaterial, createIslandMaterial, createTornadoMaterial, createPlumeMaterial } from './materials';
export { TerrainMesh, buildTerrainMesh, computeDisplacedY } from './terrain-mesh';
export { HexStateTexture } from './hex-state-texture';
export { TerrainCompute, GpuTerrainProvider, terrainFromId, elementFromId, flavorFromId } from './terrain-compute';
export { MeshCompute } from './mesh-compute';
export { IslandClassify } from './island-classify';
export { buildIslandMesh } from './island-mesh';
export { buildTornadoMesh } from './tornado-mesh';
export type { TornadoDescriptor } from './tornado-mesh';
export { buildPlumeMesh } from './plume-mesh';
export type { PlumeDescriptor } from './plume-mesh';
export { getViewProjection, screenToGround, worldToScreen, getEyePosition } from './camera';
export type { OrbitalCamera } from './camera';
export { encodeR, encodeG, encodeB, encodeA } from './hex-state-codec';
export { TERRAIN_ORDER, OBJECT_FLAGS, ISLAND_VERTEX_STRIDE, ISLAND_VERTEX_BYTE_STRIDE, TORNADO_VERTEX_STRIDE, TORNADO_VERTEX_BYTE_STRIDE } from './types';
export type { GpuContext } from './types';
export type { SceneMesh, Material, SceneObject } from './scene';
export type { GpuTerrainResult } from './terrain-compute';
export type { MeshBuffers, TerrainGridData, TerrainMeshResult } from './terrain-mesh';
export type { IslandMeshResult } from './island-mesh';
export type { IslandReadbackData } from './island-classify';
