import { TerrainType, TerrainElement } from '../core/types';

// --- GPU ↔ CPU terrain ID mappings ---

// Canonical terrain type → shader ID mapping.
// Index = shader constant (T_WATER=0, T_DESERT=1, ...).
// First 8 are base types (generated by world); 8+ are mutation-only types.
// This is the SINGLE SOURCE OF TRUTH for terrain↔ID — used by terrain-mesh.ts,
// terrain-compute.ts (WGSL T_* constants), and HexGrid.tsx (color array order).
export const TERRAIN_ORDER: readonly TerrainType[] = [
  TerrainType.WATER,       // 0
  TerrainType.DESERT,      // 1
  TerrainType.PLAIN,       // 2
  TerrainType.FOREST,      // 3
  TerrainType.MARSH,       // 4
  TerrainType.HILL,        // 5
  TerrainType.MOUNTAIN,    // 6
  TerrainType.SETTLEMENT,  // 7
  TerrainType.MAGMA,       // 8  (mutation only)
  TerrainType.CRYSTAL,     // 9  (mutation only)
  TerrainType.FLOATING,    // 10 (mutation only)
] as const;

// Derived reverse mapping: TerrainType string → shader ID.
// Used by hex-state-texture.ts to encode terrain type per hex.
export const TERRAIN_TYPE_TO_ID: Readonly<Record<string, number>> =
  Object.fromEntries(TERRAIN_ORDER.map((t, i) => [t, i]));

const ELEMENT_ORDER: readonly TerrainElement[] = [
  TerrainElement.STANDARD,
  TerrainElement.FEATURE,
  TerrainElement.RESOURCE,
  TerrainElement.DIFFICULT,
  TerrainElement.SECRET,
  TerrainElement.HUNTING_GROUND,
] as const;

// Flavor strings indexed by ID (must match WGSL FLAVOR_* constants)
const FLAVOR_TABLE: readonly string[] = [
  'Deep Ocean',        // 0
  'Shallow Sea',       // 1
  'River',             // 2
  'Bare Peak',         // 3
  'Snow-Capped Peak',  // 4
  'Rocky Bluffs',      // 5
  'Wooded Hills',      // 6
  'Barren Waste',      // 7
  'Arid Scrubland',    // 8
  'Deep Swamp',        // 9
  'Wetland',           // 10
  'Dense Forest',      // 11
  'Light Woodland',    // 12
  'Grassland',         // 13
  'Dry Plains',        // 14
  'Wilderness',        // 15
] as const;

export function terrainFromId(id: number): TerrainType {
  return TERRAIN_ORDER[id] ?? TerrainType.PLAIN;
}

export function elementFromId(id: number): TerrainElement {
  return ELEMENT_ORDER[id] ?? TerrainElement.STANDARD;
}

export function flavorFromId(id: number): string {
  return FLAVOR_TABLE[id] ?? 'Wilderness';
}

// --- GPU context ---

export interface GpuContext {
  readonly adapter: GPUAdapter;
  readonly device: GPUDevice;
}

// --- Mesh vertex data layout for terrain rendering ---
// Each vertex: posX(1) + posZ(1) + elevation(1) + moisture(1) + normalXYZ(3) = 7 floats = 28 bytes
// Terrain type is resolved per-fragment from the hex state texture (Layer 3), not per-vertex.
export const MESH_VERTEX_STRIDE = 7;
export const MESH_VERTEX_BYTE_STRIDE = MESH_VERTEX_STRIDE * 4;
